services:
  emulator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/emulator
    ports:
      - "3333:3333"
    tty: true
    labels:
      - dev.orbstack.http-port=3333
    depends_on:
      - db

  db:
    image: postgres:18-alpine3.23
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      POSTGRES_DB: "cube-emulator"
      POSTGRES_USER: "cube-emulator"
      POSTGRES_PASSWORD: "cube-emulator"
    volumes:
      - dbdata:/var/lib/postgresql
    labels:
      - dev.orbstack.http-port=5432

volumes:
  dbdata:
