services:
  emulator:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./:/emulator
    ports:
      - "3333:3333"
    command:
      - "npm"
      - "run"
      - "dev"
